name: gr8plugin
main: com.smithster.gr8plugin.Plugin
version: 0.0.1
api-version: 1.15
commands:
   arena:
      description: Create an arena
      usage: /<command> type args
      permission: gr8plugin.arena
   plot:
      description: Create a plot, or edit an existing plots values
      usage: /<command> (create [name]) OR ([name] [function] [value])
      permission: gr8plugin.plot