name: gr8plugin
main: com.smithster.gr8plugin.Plugin
version: 0.0.1
api-version: 1.15
commands:
   arena:
      description: Create an arena
      usage: /<command> type args
      permission: gr8plugin.arena
   plot:
      description: Create a plot
      usage: /<command> name [1 or 2]
      permission: gr8plugin.plot